version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    container_name: code-reviewer-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: mongod --auth

  backend:
    build: ./backend
    container_name: code-reviewer-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo-db:27017/code-reviewer?authSource=admin
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: code-reviewer-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

